### ISSUE TITLE
Fedora 32  Gnome updates have killed 2020 and other extensions

### ISSUE THREAD

**Issue by lsatenstein** [c0ldplasma/gnome-shell-extension-taskbar#13]
Sadly, my preferred gnome extensions  sensors, Taskbar 2020 have stopped working.

By the way, even the backup Taskbar@zpydr has failed.

Fedora 32

**Comment by lsatenstein** [comment]
I got this from the sensors debug  

GnomeShell Syntax issue,  Not a Taskbar 2020 issue,

SyntaxError: missing ( after for

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by c0ldplasma** [comment]
I checked all for loops of Taskbar and they all seem correct. I think there is only a problem with the sensors extension, as the "for each" loops they still use in there were deprecated in javascript a while ago. Someone there suggested a solution: https://github.com/xtranophilist/gnome-shell-extension-sensors/issues/150

**Comment by Shnoulle** [comment]
I'm on Fedora 32 : TaskBar 2020 seems to work like a charm.

(Thank you)
