### ISSUE TITLE
Main.overview._dash is undefined

### ISSUE THREAD

**Issue by svobs** [c0ldplasma/gnome-shell-extension-taskbar#14]
Running Ubuntu 20.04 with a gnome-shell X session
Linux matt-xps13 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Did a routine update of the Ubuntu software today and it required a restart. After the restart, I found that TaskBar 2020 was broken.

I don't know much about Gnome Shell extensions, but I was able to use the 'lg' utility to see the following error:
Main.overview._dash is undefined

**Comment by c0ldplasma** [comment]
Main.overview._dash is something gnome-shell provides. Weird that this is undefined. Could not reproduce the error on my Ubuntu 20.04 VM.

Only thing i can suggest for now is to try to reinstall the extension and make sure it really gets deleted from ~/.local/share/gnome-shell/extensions before installing it again.

**Comment by svobs** [comment]
Strangely the problem cleared up after a couple of restarts and I was able to enable the plugin again. Maybe a strange artifact caused by one of the subsystems getting updated? I'll close this issue. Thanks for your quick reply.
