### ISSUE TITLE
Just shows "Error" when I try and install it

### ISSUE THREAD

**Issue by mvandemar** [c0ldplasma/gnome-shell-extension-taskbar#18]
I just switched from Fedora 30 to Centos 7. I am using Gnome 3.28. I attempted to install both via the extensions.gnome.org interface and by downloading the zip for my version of Gnome, but in both instances I just get a red Error button instead of the activate/deactivate option.

**Comment by c0ldplasma** [comment]
Gnome 3.28 is not supported. Use the old Taskbar extension version linked in the readme.
