### ISSUE TITLE
Don't work on 20.10

### ISSUE THREAD

**Issue by vadbars** [c0ldplasma/gnome-shell-extension-taskbar#19]
Thanks for the great extension. Worked well on 20.04. But... Don't work now on Ubuntu 20.10 (Pop!_os, kernel 5.8.9, gnome 3.38.0).

**Comment by c0ldplasma** [comment]
Fixed it with version 5. Will take some time for it to be available on extensions.gnome.org but you can download it on the releases page here on github.
