### ISSUE TITLE
Bottom panel centered is not centered

### ISSUE THREAD

**Issue by danogh** [c0ldplasma/gnome-shell-extension-taskbar#20]
I'm working on some enhancements to this extension such as a workspace switcher.  While working on it, I noticed that when the bottom panel is centered it is actually not quite centered.

The fix is rather simple.  I've cloned the repository, made the changes, and tested it.

Should I push my changes or is there a better way submit changes?

Thanks,

Dan

**Comment by c0ldplasma** [comment]
Thanks for submitting the issue and your work on the project.

To submit new features or fixes fork the repository, create a new branch, push your changes there and then create a pull request.

**Comment by danogh** [comment]
Pull request submitted
