### ISSUE TITLE
Broken on GNOME 40 please fix

### ISSUE THREAD

**Issue by goirik-chakrabarty** [c0ldplasma/gnome-shell-extension-taskbar#29]
Sorry for not adhering to the format in advance.

**To Reproduce**
Download Gnome 40 on Manjaro 21

**Expected behavior**
Dialogue box for preference broken. GNOME 40 mandates GTK4 dialogue boxes for extension 

**Desktop (please complete the following information):**
 - OS and version: Manjaro 21.1
 - GNOME Shell Version 40
 - TaskBar 2020 Version latest

This is one of my core extensions please update.

**Comment by c0ldplasma** [comment]
Made an initial working release for gnome 40 comptibility. Some things are still broken though.

**Comment by GaVenga** [comment]
Changing Color on Top panel does not work (the same in Dash To Panel)
**_Works on Bottom Panel_**

    OS and version: Manjaro 21.1
    GNOME Shell Version 40.0.1
    TaskBar 2020 Version latest
